version: "3.9"
services:
    frontend:
        image: yarema2000/diploma-frontend:1.0
        container_name: frontend
        ports:
            - 4200:80
    backend:
        image: yarema2000/diploma-backend:1.1
        container_name: backend
        ports:
            - 8080:8080
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/scientometric_project
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SENDGRID_API_KEY: 
            FROM_EMAIL: amerscan8+from@gmail.com
            FRONTEND_URL: http://localhost:4200
            ACCESS_TOKEN_SECRET: =============DiplomaAccessTokenSecret============
            REFRESH_TOKEN_SECRET: =============DiplomaRefreshTokenSecret============
        depends_on:
            - db
    db:
        image: postgres:15
        container_name: db
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=scientometric_project
            - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
    pgdata:
