CREATE TABLE extraction_profiles
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_finished   BOOLEAN,
    extraction_id INTEGER,
    profile_id    INTEGER,
    CONSTRAINT pk_extraction_profiles PRIMARY KEY (id)
);

ALTER TABLE extraction_profiles
    ADD CONSTRAINT FK_EXTRACTION_PROFILES_ON_EXTRACTION FOREIGN KEY (extraction_id) REFERENCES extractions (id);

ALTER TABLE extraction_profiles
    ADD CONSTRAINT FK_EXTRACTION_PROFILES_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profiles (id);