CREATE TABLE user_permissions
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       INTEGER,
    permission_id INTEGER,
    CONSTRAINT pk_user_permissions PRIMARY KEY (id)
);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);