CREATE TABLE field_recommendations
(
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key                     VARCHAR(255),
    text                    VARCHAR(255),
    scientometric_system_id INTEGER,
    field_id                INTEGER,
    recommendation_type_id  INTEGER,
    CONSTRAINT pk_field_recommendations PRIMARY KEY (id)
);

CREATE TABLE profile_field_recommendations
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_condition_fulfilled BOOLEAN                                  NOT NULL,
    profile_field_value_id INTEGER,
    CONSTRAINT pk_profile_field_recommendations PRIMARY KEY (id)
);

CREATE TABLE recommendation_types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_recommendation_types PRIMARY KEY (id)
);

ALTER TABLE field_recommendations
    ADD CONSTRAINT FK_FIELD_RECOMMENDATIONS_ON_FIELD FOREIGN KEY (field_id) REFERENCES fields (id);

ALTER TABLE field_recommendations
    ADD CONSTRAINT FK_FIELD_RECOMMENDATIONS_ON_RECOMMENDATION_TYPE FOREIGN KEY (recommendation_type_id) REFERENCES recommendation_types (id);

ALTER TABLE field_recommendations
    ADD CONSTRAINT FK_FIELD_RECOMMENDATIONS_ON_SCIENTOMETRIC_SYSTEM FOREIGN KEY (scientometric_system_id) REFERENCES scientometric_systems (id);

ALTER TABLE profile_field_recommendations
    ADD CONSTRAINT FK_PROFILE_FIELD_RECOMMENDATIONS_ON_PROFILE_FIELD_VALUE FOREIGN KEY (profile_field_value_id) REFERENCES profile_field_values (id);