server:
  port: 8080
spring:
  application:
    name: APIApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/scientometric_project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    baseline-version: 0

email_service:
  api-key: "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"
  from-email: "amerscan8+from@gmail.com"
  frontend-url: "http://localhost:4200"

app:
  jwt:
    access-token-secret: "==================ApiApplicationSecretAccessTokenKey====================="
    refresh-token-secret: "==================ApiApplicationSecretRefreshTokenKey====================="
    expiration-ms: 3600000
    refresh-expiration-ms: 86400000

scholar:
  faculty_source: db/scholar_init/chairs-list-2024.xlsx
  scientist_scholar_source: db/scholar_init/scholar-list.xlsx
  chair_prefix: "кафедра"
  faculty_prefix: "факультет"
  basic_url: "https://scholar.google.com.ua"