server:
  port: 8080
spring:
  application:
    name: APIApplication
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    baseline-version: 0
    validate-on-migrate: false

email_service:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${FROM_EMAIL}
  frontend-url: ${FRONTEND_URL}

app:
  jwt:
    access-token-secret: ${ACCESS_TOKEN_SECRET}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    expiration-ms: 3600000
    refresh-expiration-ms: 86400000

scholar:
  faculty_source: db/scholar_init/chairs-list-2024.xlsx
  scientist_scholar_source: db/scholar_init/scholar-list.xlsx
  chair_prefix: "кафедра"
  faculty_prefix: "факультет"
  basic_url: "https://scholar.google.com.ua"